Pizzeria
pkaraseva18214/OOP pull request #3
Opened 2020-05-24 10:59 UTC by pkaraseva18214

2020-07-20 03:12 UTC, pkaraseva18214 commented
Посмотрите, пожалуйста, изменения.

2020-07-24 11:01 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Baker.java
> +          e.printStackTrace();
Полина, я уже столько раз задавал одни и те же вопросы к `e.printStackTrace()`, чтобы можно было заподозрить, что так делать не надо. Давай ещё раз: 
- является ли штатной (ожидаемой) ситуацией возникновение этого исключения, или при любом сценарии работы программы оно не должно выбрасываться?
- если нет, при каком сценарии работы программы оно возникает? Я имею в виду именно действия твоего собственного кода; то, что оно выбрасывается при прерывании потока, мы уже выяснили.
- является ли адекватной реакцией на его возникновение печать stack trace - что с точки зрения программы равно "ничего не делать"?
- необходимо ли пользователю видеть этот stacktrace и скажет ли ему эта информация что-нибудь?

2020-07-24 11:02 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Baker.java
> +    } catch (NullPointerException e) {
Для чего это здесь? Где может возникать `NullPointerException` и почему при его возникновении ничего не надо делать?

2020-07-24 11:04 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Bakers.java
> +    ExecutorService executorService = Executors.newFixedThreadPool(employees.getNumberOfBakers());
Я ожидаю, что ты уберёшь здесь тредпул и переделаешь на использование индивидуальных потоков. Тредпул нужен в других ситуациях

2020-07-24 11:08 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/DeliveryWorker.java
> +  void setStorage(ArrayBlockingQueue<Order> itemsInStorage) {
Тот же вопрос, что и к `Baker`: зачем выносить это в отдельный от конструктора метод? Так как `itemsInStorage` является необходимым для работы класса, его нужно инициализировать в конструкторе - только так можно гарантировать, что в момент необходимости доступа к очереди она действительно будет существовать. А методы-сеттеры нужны только если значение поля нужно поменять в процессе работы программы, но никак не для его инициализации.

2020-07-24 11:09 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/DeliveryWorker.java
> +            && itemsInStorage.size() == 0
Эти условия проверяются в условии цикла - зачем их дублировать здесь?

2020-07-24 11:10 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/DeliveryWorker.java
>        deliveryWorkers.lock.lock();
Тот же самый вопрос про необходимость этого `lock`.

2020-07-24 11:19 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Pizzeria.java
>      closePizzeria();
Это очень странно, что ты закрываешь пиццерию сразу после её старта. Чуть менее странно то, что все заказы приходят в пиццерию одновременно

2020-07-24 11:21 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/PizzeriaOverview.java
> +      pizzeriaIsClosed = true;
Довольно странно, что ты синхронизируешь доступ к `pizzeriaIsClosed` при записи, но не синхронизируешь - при чтении. Кроме того, где гарантия, что ВМ не закеширует значение переменной для каждого отдельного потока, и они вовремя увидят это изменение?

2020-07-24 11:23 UTC, alex-ks commented on Task_2_1_1/src/test/java/ru/nsu/fit/karaseva/pizzeria/DataTest.java
> +    Assert.assertEquals(1, employees.getBakers().get(0).getId());
Если ты хочешь проверить чтение из JSON, проверяй содержимое классов *Config. Если ты хочешь проверить конструирование работников из этих конфигураций, не читай конфигурации из файла, а собирай их руками. Иначе, если тест провалится, то будет непонятно, в каком их этих двух разных сценариев произошла ошибка

2020-07-24 11:25 UTC, alex-ks commented on Task_2_1_1/src/test/java/ru/nsu/fit/karaseva/pizzeria/WorkTest.java
> +    File deliveryFile = new File("src/main/resources/input");
Читай данные из файла только в тестах на чтение конфигурации из файла. Во всех остальных местах используй готовые объекты

2020-07-24 11:48 UTC, alex-ks commented on Task_2_1_1/src/test/java/ru/nsu/fit/karaseva/pizzeria/DataTest.java
> +    File deliveryFile = new File("src/main/resources/input");
Почему конфиг для доставки называется input?

2020-09-01 16:03 UTC, pkaraseva18214 commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Baker.java
> +          bakers.lock.lock();
Для синхронизации, но видимо от него только хуже

2020-09-08 15:45 UTC, alex-ks requested changes
Здесь три основные проблемы:
- работа с потоками реализована через неподходящий примитив
- используются лишние примитивы синхронизации
- поступление новых заказов не соответствует условиям моделируемого процесса (работы пиццерии)

Кроме того, здесь присутствует неиспользуемый код самописной очереди, который надо удалить, а тесты пытались выполниться в течение 26 минут, но не смогли.

Это всё не выглядит сложными неисправимыми проблемами, так что давай их поправим - это будет полезной практикой. И ещё предлагаю в обработчиках невозможных исключений ставить `assert false;`.

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/PizzeriaOverview.java
> +      pizzeriaIsClosed = true;
Операции чтения и присвоения примитивных типов в Java происходят атомарно, за исключением `double` и `long` (другие операции, например, инкремент, атомарными не являются). Но JVM при этом имеет право не синхронизировать эти изменения в кэшах разных ядер, т.к. это дорогая операция. Чтобы гарантировать, что любой поток всегда имеет доступ к актуальному значению, нужно использовать ключевое слово `volatile`.

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Pizzeria.java
>      closePizzeria();
Ещё раз обращаю внимание на странность дизайна с поступлением заказов. С точки зрения моделируемой ситуации, заказы поступают в случайное время дня, что может вызвать простои работников - выявление таких простоев и есть одна из задач моделирования. Здесь же изначально моделируется невозможная ситуация: на работников в самом начале дня вываливается ушат заказов, и весь день они пытаются его разобрать. С точки зрения симуляции предметной области написанное решение не справляется со своей задачей

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Bakers.java
> +    ExecutorService executorService = Executors.newFixedThreadPool(employees.getNumberOfBakers());
Причину неприменимости тредпула я описал выше. Предполагалось решение с помощью класса `Thread`: работник держит у себя в качестве поля экземпляр потока, передаёт ему объект `Runnable` (который содержит в себе основной метод работника) и управляет временем жизни этого потока. Класс "работник", который бы как раз управлял потоком, был бы абстрактным, т.к. эта логика была бы общей и для пекарей, и для курьеров. Пекари и курьеры переопределяли бы только свой основной рабочий цикл.

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/DeliveryWorker.java
> +  void setStorage(ArrayBlockingQueue<Order> itemsInStorage) {
Так почему эту очередь нельзя передавать в конструкторе?

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/DeliveryWorker.java
>        deliveryWorkers.lock.lock();
Up. Изменения каких данных синхронизирует этот lock, если очередь заказов и флаги состояний уже синхронизрованы?

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Baker.java
> +  public void setAdditionalParameters(
Up. Почему это нельзя передавать в конструкторе?

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Baker.java
> +      ;
Зачем эта `;` здесь?

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Baker.java
> +      this.waitingForOrder = true;
Для чего нужен этот флаг?

2020-09-08 15:45 UTC, alex-ks commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Baker.java
> +          bakers.lock.lock();
Синхронизации чего с чем? Твоя очередь и флаги состояний уже должны быть синхронными, другого разделяемого состояния у пекарей не видится. "Хуже" - не очень корректное обстоятельство, он выглядит бессмысленным.

2020-09-11 15:07 UTC, pkaraseva18214 commented on Task_2_1_1/src/main/java/ru/nsu/fit/karaseva/pizzeria/Baker.java
> +      ;
Не заметила, лишняя.

2020-09-23 16:48 UTC, closed without merging